server:
  port: 8082
  servlet:
    application-display-name: idfa
    context-path: /idfa
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db1:
        username: root
        password: w1q2e3r4
        url: jdbc:mysql://121.40.138.84:3306/idfa?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
      db2:
        username: root
        password: w1q2e3r4
        url: jdbc:mysql://121.40.138.84:3306/idfa?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
      db3:
        username: root
        password: w1q2e3r4
        url: jdbc:mysql://121.40.138.84:3306/idfa?useUnicode=true&amp;characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
#扫描pojo类的位置,在此处指明扫描实体类的包，在mapper中就可以不用写pojo类的全路径名了
mybatis-plus:
  #mybatis mapper文件的位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.wlwq.idfa.entity
  #SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句,REUSE：该执行器类型会复用预处理语句,BATCH：该执行器类型会批量执行所有的更新语句
  default-executor-type: REUSE
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      #是否开启大写命名，默认不开启
      #capital-mode: false
      #逻辑已删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
      logic-not-delete-value: 0
      #逻辑未删除值,(逻辑删除下有效)
      logic-delete-value: 1
      #数据库类型
      db-type: mysql
